// Package interop verifies output produced by mcp-searxng-relay's own
// fence.go. It is the only test that can catch a bug present in both the
// gateway's verifier and its reference generator: everything in fenceverify
// is checked against fenceverify.Generate, which would hide any mistake the
// two share.
//
// The vectors under testdata/relay are generated by regen.sh from the relay
// commit pinned in testdata/relay/RELAY_COMMIT. CI also regenerates them into
// a scratch directory and points INTEROP_VECTORS at it, so a relay format
// change is caught when the pin moves rather than in production.
package interop

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	fv "github.com/littleoffice/fence-gateway/fenceverify"
)

// Vector is one generated tool response and what its content fence must
// verify to. See relaygen/main.go.
type Vector struct {
	Name     string `json:"name"`
	File     string `json:"file"`
	Layout   string `json:"layout"`
	Encoding string `json:"encoding"`
	Type     string `json:"type"`
	Source   string `json:"source"`
	Content  string `json:"content"`
}

// awarenessSource is the source attribute of the 1.1 trusted preamble fence.
const awarenessSource = "mcp-searxng-relay:awareness"

func vectorDir() string {
	if d := os.Getenv("INTEROP_VECTORS"); d != "" {
		return d
	}
	return filepath.Join("testdata", "relay")
}

func loadVectors(t *testing.T) (string, ed25519.PublicKey, []Vector) {
	t.Helper()
	dir := vectorDir()
	raw, err := os.ReadFile(filepath.Join(dir, "pub.b64"))
	if err != nil {
		t.Fatalf("read public key: %v", err)
	}
	pk, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(raw)))
	if err != nil || len(pk) != ed25519.PublicKeySize {
		t.Fatalf("decode public key: %v (%d bytes)", err, len(pk))
	}
	manifest, err := os.ReadFile(filepath.Join(dir, "vectors.json"))
	if err != nil {
		t.Fatalf("read manifest: %v", err)
	}
	var vs []Vector
	if err := json.Unmarshal(manifest, &vs); err != nil {
		t.Fatalf("parse manifest: %v", err)
	}
	if len(vs) == 0 {
		t.Fatal("manifest lists no vectors")
	}
	return dir, pk, vs
}

func readVector(t *testing.T, dir string, v Vector) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, v.File))
	if err != nil {
		t.Fatalf("read %s: %v", v.File, err)
	}
	return string(b)
}

func verifier(pk ed25519.PublicKey) *fv.Verifier {
	return &fv.Verifier{Keys: []ed25519.PublicKey{pk}, Scheme: fv.SchemeRelay, RequireNonce: true}
}

// Every vector verifies, the content fence recovers the exact bytes the relay
// signed, and the layout is what its version says it is.
func TestRelayVectorsVerify(t *testing.T) {
	dir, pk, vs := loadVectors(t)
	kid := fv.Fingerprint(pk)
	for _, v := range vs {
		t.Run(v.Name, func(t *testing.T) {
			res, err := verifier(pk).Verify(readVector(t, dir, v))
			if err != nil {
				t.Fatalf("verify: %v", err)
			}
			if len(res.Rejections) != 0 {
				t.Fatalf("rejections: %+v", res.Rejections)
			}

			var content *fv.Fence
			for i := range res.Fences {
				f := &res.Fences[i]
				if f.Extra["kid"] != kid {
					t.Errorf("fence kid = %q, want %q", f.Extra["kid"], kid)
				}
				if f.Extra["version"] != v.Layout {
					t.Errorf("fence version = %q, want %q", f.Extra["version"], v.Layout)
				}
				if f.Rating == fv.RatingUntrusted {
					content = f
				}
			}
			if content == nil {
				t.Fatalf("no untrusted content fence among %d verified", len(res.Fences))
			}
			if content.Content != v.Content {
				t.Errorf("content not byte-exact:\n got %q\nwant %q", content.Content, v.Content)
			}
			if content.Encoding != v.Encoding || content.Source != v.Source || content.Type != v.Type {
				t.Errorf("got encoding=%q source=%q type=%q, want %q %q %q",
					content.Encoding, content.Source, content.Type, v.Encoding, v.Source, v.Type)
			}

			switch v.Layout {
			case "1.0":
				// One fence, and the prose preamble in front of it unsigned.
				if len(res.Fences) != 1 || len(res.UnsignedRegions) != 1 {
					t.Errorf("1.0: want 1 fence and 1 unsigned region, got %d and %d",
						len(res.Fences), len(res.UnsignedRegions))
				}
			case "1.1":
				// Two fences and nothing unsigned: the preamble travels in a
				// trusted fence of its own, naming the content fence's nonce.
				if len(res.Fences) != 2 || len(res.UnsignedRegions) != 0 {
					t.Fatalf("1.1: want 2 fences and no unsigned text, got %d and %d",
						len(res.Fences), len(res.UnsignedRegions))
				}
				pre := res.Fences[0]
				if pre.Rating != fv.RatingTrusted || pre.Type != fv.TypeInstructions || pre.Source != awarenessSource {
					t.Errorf("1.1 preamble fence: rating=%q type=%q source=%q", pre.Rating, pre.Type, pre.Source)
				}
				if !strings.Contains(pre.Content, `nonce="`+content.Nonce+`"`) {
					t.Error("1.1 preamble does not name the content fence's nonce")
				}
			default:
				t.Errorf("unknown layout %q", v.Layout)
			}
		})
	}
}

// Changing a signed attribute of a real relay fence breaks it — including
// encoding, which decides which bytes the verifier reconstructs.
func TestRelayVectorsTamperingRejected(t *testing.T) {
	dir, pk, vs := loadVectors(t)
	for _, v := range vs {
		t.Run(v.Name, func(t *testing.T) {
			s := readVector(t, dir, v)
			// Edit the content fence's opening tag, which is the last real
			// fence in both layouts. The preamble prose also mentions
			// rating="untrusted", so a plain first-match replace would edit
			// that instead.
			at := strings.LastIndex(s, "<sec:fence xmlns")
			if at < 0 {
				t.Fatal("no fence element found")
			}
			edit := func(old, new string) string {
				return s[:at] + strings.Replace(s[at:], old, new, 1)
			}
			tampered := []string{edit(`rating="untrusted"`, `rating="trusted"`)}
			if v.Encoding == fv.EncodingCDATA {
				tampered = append(tampered, edit(` encoding="cdata"`, ""))
			}
			for i, x := range tampered {
				if x == s {
					t.Fatalf("tamper %d changed nothing", i)
				}
				res, err := verifier(pk).Verify(x)
				if err != nil {
					t.Fatalf("verify: %v", err)
				}
				if len(res.Rejections) == 0 {
					t.Errorf("tamper %d was not rejected", i)
				}
				for _, f := range res.Fences {
					if f.Rating == fv.RatingUntrusted || f.Source == v.Source {
						t.Errorf("tamper %d: the content fence still verified", i)
					}
				}
			}
		})
	}
}
